2017-10-02 14:02:33.357 [mp-conn-boss-1-1] ERROR cxf.hb.log - server start failure on:8887
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:436)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 14:08:04.341 [mp-conn-work-3-1] ERROR cxf.conn.log - client caught ex, conn=[channel=[id: 0xae34e2e7, L:/192.168.1.106:8887 - R:/192.168.1.106:30218], context=, status=1, lastReadTime=1506924484336, lastWriteTime=0]
2017-10-02 14:08:04.343 [mp-conn-work-3-1] ERROR cxf.conn.log - caught an ex, channel=[id: 0xae34e2e7, L:/192.168.1.106:8887 - R:/192.168.1.106:30218], conn=[channel=[id: 0xae34e2e7, L:/192.168.1.106:8887 - R:/192.168.1.106:30218], context=, status=1, lastReadTime=1506924484336, lastWriteTime=0]
java.lang.IndexOutOfBoundsException: dstIndex: 1, length: 1 (expected: range(0, 1))
	at io.netty.buffer.AbstractByteBuf.checkDstIndex(AbstractByteBuf.java:1369)
	at io.netty.buffer.UnpooledHeapByteBuf.getBytes(UnpooledHeapByteBuf.java:176)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:851)
	at com.cxf.netty.tcp.convent.Msg.conventMsg(Msg.java:39)
	at com.cxf.netty.tcp.ServerTCPHandler.channelRead(ServerTCPHandler.java:43)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 14:15:41.234 [mp-conn-boss-1-1] ERROR cxf.hb.log - server start failure on:8887
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:436)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 16:48:49.520 [mp-conn-boss-1-1] ERROR cxf.hb.log -
				server start failure on:8888
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:436)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 16:49:06.991 [mp-conn-boss-1-1] ERROR cxf.hb.log -
				server start failure on:8888
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:436)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 16:53:01.209 [mp-conn-work-3-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 16:53:11.214 [mp-conn-work-3-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 16:53:21.220 [mp-conn-work-3-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 16:53:31.227 [mp-conn-work-3-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 16:53:41.235 [mp-conn-work-3-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 20:28:07.121 [mp-conn-boss-1-1] ERROR cxf.hb.log -
				server start failure on:8888
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:436)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 20:28:19.659 [mp-conn-boss-1-1] ERROR cxf.hb.log -
				server start failure on:8888
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:436)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 22:21:05.995 [mp-boss-4-1] ERROR cxf.hb.log -
				server start failure on:8887
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:436)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 22:22:25.498 [mp-boss-4-1] ERROR cxf.hb.log -
				server start failure on:8887
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:436)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 22:26:11.602 [mp-work-5-1] ERROR cxf.conn.log -
				client caught ex, conn=null
2017-10-02 23:08:45.978 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-02 23:08:55.988 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:09:05.996 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:09:16.004 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:09:26.012 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:09:36.020 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:10:51.151 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-02 23:11:01.158 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:11:11.164 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:11:21.180 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:11:31.190 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:11:41.198 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:11:51.205 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:12:01.212 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:12:11.234 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:12:21.243 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:12:31.248 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:16:01.150 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-02 23:16:11.160 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:16:21.170 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:16:31.180 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:16:41.188 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:16:51.196 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:17:01.206 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:17:11.211 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:21:48.097 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-02 23:21:58.108 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:22:08.117 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:22:18.124 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:22:28.124 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:22:38.129 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:22:48.131 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:22:58.144 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:23:08.147 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:23:18.149 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:23:28.150 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:26:04.086 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-02 23:26:25.426 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-02 23:26:35.437 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:26:45.445 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:26:55.452 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:27:05.457 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:27:15.462 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:27:25.466 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:27:35.479 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:27:45.482 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:27:55.486 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:28:05.489 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:32:08.437 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-02 23:33:48.224 [mp-conn-work-5-1] ERROR cxf.conn.log -
				client caught ex, conn=[channel=[id: 0xe53033c2, L:/192.168.1.106:8887 - R:/192.168.1.106:4304], context=, status=1, lastReadTime=1506958328426, lastWriteTime=1506958363847]
2017-10-02 23:33:48.227 [mp-conn-work-5-1] ERROR cxf.conn.log -
				caught an ex, channel=[id: 0xe53033c2, L:/192.168.1.106:8887 - R:/192.168.1.106:4304], conn=[channel=[id: 0xe53033c2, L:/192.168.1.106:8887 - R:/192.168.1.106:4304], context=, status=1, lastReadTime=1506958328426, lastWriteTime=1506958363847]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 23:37:35.623 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-02 23:38:28.191 [mp-conn-work-5-1] ERROR cxf.conn.log -
				client caught ex, conn=[channel=[id: 0xb33d2afb, L:/192.168.1.106:8887 - R:/192.168.1.106:4383], context=, status=1, lastReadTime=1506958655611, lastWriteTime=1506958667541]
2017-10-02 23:38:28.194 [mp-conn-work-5-1] ERROR cxf.conn.log -
				caught an ex, channel=[id: 0xb33d2afb, L:/192.168.1.106:8887 - R:/192.168.1.106:4383], conn=[channel=[id: 0xb33d2afb, L:/192.168.1.106:8887 - R:/192.168.1.106:4383], context=, status=1, lastReadTime=1506958655611, lastWriteTime=1506958667541]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-02 23:39:39.484 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-02 23:39:49.431 [mp-work-3-1] ERROR cxf.conn.log -
				client caught ex, conn=null
2017-10-02 23:39:49.489 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:39:59.492 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:40:09.497 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:40:19.501 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:40:29.503 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:40:39.503 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:40:49.506 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:40:59.508 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-02 23:41:00.574 [mp-conn-work-5-2] ERROR cxf.conn.log -
				client caught ex, conn=[channel=[id: 0xc66e8fd4, L:/192.168.1.106:8887 - R:/192.168.1.106:4412], context=, status=1, lastReadTime=1506958859508, lastWriteTime=1506958792719]
2017-10-02 23:41:00.574 [mp-conn-work-5-2] ERROR cxf.conn.log -
				caught an ex, channel=[id: 0xc66e8fd4, L:/192.168.1.106:8887 - R:/192.168.1.106:4412], conn=[channel=[id: 0xc66e8fd4, L:/192.168.1.106:8887 - R:/192.168.1.106:4412], context=, status=1, lastReadTime=1506958859508, lastWriteTime=1506958792719]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
