2017-10-07 21:25:17.369 [main] ERROR com.cxf.netty.tcp.convent.Msg -
				sign error
2017-10-07 21:25:44.816 [main] ERROR com.cxf.netty.tcp.convent.Msg -
				sign error
2017-10-07 21:27:54.909 [main] ERROR com.cxf.netty.tcp.convent.Msg -
				sign error
2017-10-07 21:32:17.964 [main] ERROR com.cxf.netty.tcp.convent.Msg -
				sign error
2017-10-07 21:49:59.714 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				sign error
2017-10-07 21:50:09.721 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				sign error
2017-10-07 21:50:19.725 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				sign error
2017-10-07 21:50:28.396 [mp-conn-work-5-1] ERROR cxf.conn.log -
				client caught ex, conn=[channel=[id: 0xef64df3d, L:/192.168.1.106:8887 - R:/192.168.1.106:2220], context=, status=1, lastReadTime=1507384219724, lastWriteTime=0]
2017-10-07 21:50:28.414 [mp-conn-work-5-1] ERROR cxf.conn.log -
				caught an ex, channel=[id: 0xef64df3d, L:/192.168.1.106:8887 - R:/192.168.1.106:2220], conn=[channel=[id: 0xef64df3d, L:/192.168.1.106:8887 - R:/192.168.1.106:2220], context=, status=1, lastReadTime=1507384219724, lastWriteTime=0]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-07 21:52:04.457 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-07 21:52:14.469 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:52:24.475 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:52:34.482 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:52:44.488 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:52:54.499 [mp-conn-work-5-1] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:53:00.793 [mp-conn-work-5-1] ERROR cxf.conn.log -
				client caught ex, conn=[channel=[id: 0xf61ca9ea, L:/192.168.1.106:8887 - R:/192.168.1.106:2299], context=, status=1, lastReadTime=1507384374493, lastWriteTime=0]
2017-10-07 21:53:00.795 [mp-conn-work-5-1] ERROR cxf.conn.log -
				caught an ex, channel=[id: 0xf61ca9ea, L:/192.168.1.106:8887 - R:/192.168.1.106:2299], conn=[channel=[id: 0xf61ca9ea, L:/192.168.1.106:8887 - R:/192.168.1.106:2299], context=, status=1, lastReadTime=1507384374493, lastWriteTime=0]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
2017-10-07 21:54:57.828 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.register.url is null:
2017-10-07 21:55:07.836 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:55:17.844 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:55:27.851 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:55:37.858 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:55:47.861 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:55:57.865 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:56:07.871 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:56:17.875 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:56:27.882 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 21:56:37.890 [mp-conn-work-5-2] ERROR com.cxf.netty.tcp.convent.Msg -
				error system.location.url is null:
2017-10-07 22:08:44.730 [mp-conn-work-5-2] ERROR cxf.conn.log -
				client caught ex, conn=[channel=[id: 0xe3ff5e9f, L:/192.168.1.106:8887 - R:/192.168.1.106:2388], context=, status=1, lastReadTime=1507384597889, lastWriteTime=0]
2017-10-07 22:08:44.730 [mp-conn-work-5-2] ERROR cxf.conn.log -
				caught an ex, channel=[id: 0xe3ff5e9f, L:/192.168.1.106:8887 - R:/192.168.1.106:2388], conn=[channel=[id: 0xe3ff5e9f, L:/192.168.1.106:8887 - R:/192.168.1.106:2388], context=, status=1, lastReadTime=1507384597889, lastWriteTime=0]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
